### ISSUE TITLE
Issues checklist for next release

### ISSUE THREAD

**Issue by wiiaboo** [wiiaboo/Wanikani-Notifier#1]
- [x] Update check occasionally doesn't work
- [x] Clicking browser action shouldn't open a new tab if there's another one to a `/session` already open, it breaks some user scripts
- [x] Add command to do a manual update
- [x] Update to v2 API
   - [x] Support v2 API request caching and 304 responses
- [x] Find a way to display information about both lessons and reviews
- [x] Maybe also add a command to go to either lessons or reviews session, but leave single-click as shortcut for reviews session if there any to be done
